import {
  Bot,
  BrainCircuit,
  FileText,
  Newspaper,
  Zap,
  BookOpen,
  PieChart,
  Wallet,
  GitCompare,
  BarChart3

} from "lucide-react";


export const journeys = {
  fundamentals: {
    steps: [
      { text: "Activating Fundamental Agent — spreadsheets, assemble...", duration: 1500 },
      { text: "Pulling balance sheets, income, and cash flow...", duration: 1500 },
      { text: "Crunching ratios: P/E, ROE, and more acronyms...", duration: 1500 },
      { text: "Analyzing revenue trends and profit growth...", duration: 1500 },
      { text: "Checking debt levels and financial health...", duration: 1500 },
      { text: "Examining margins — gross, operating, net...", duration: 1500 },
      { text: "Calculating return metrics: ROE, ROCE, ROI...", duration: 1500 },
      { text: "Reviewing EPS and dividend history...", duration: 1500 },
      { text: "Checking cash reserves and liquidity...", duration: 1500 },
      { text: "Analyzing asset efficiency and turnover...", duration: 1500 },
      { text: "Evaluating capital expenditure trends...", duration: 1500 },
      { text: "Benchmarking against industry peers...", duration: 1500 },
      { text: "Identifying strengths and financial red flags...", duration: 1500 },
      { text: "Calculating valuation ratios: P/B, EV/EBITDA...", duration: 1500 },
      { text: "Checking historical performance patterns...", duration: 1500 },
      { text: "Analyzing risk factors from reports...", duration: 1500 },
      { text: "Mapping profitability over quarters...", duration: 1500 },
      { text: "Summarizing key metrics in plain English...", duration: 1500 },
      { text: "Generating graphs and easy-to-read charts...", duration: 1500 },
      { text: "Finalizing fundamental report for decision-making...", duration: 1500 },
    ],
    icon: FileText,
  },
  

  technicals: {
    steps: [
      { text: "Booting Technical Agent — charts incoming...", duration: 1500 },
      { text: "Fetching historical price data...", duration: 1500 },
      { text: "Calculating moving averages...", duration: 1500 },
      { text: "Running RSI, MACD, and Stochastic indicators...", duration: 1500 },
      { text: "Detecting trendlines and patterns...", duration: 1500 },
      { text: "Spotting support and resistance levels...", duration: 1500 },
      { text: "Checking volume spikes and anomalies...", duration: 1500 },
      { text: "Scanning for breakout or breakdown signals...", duration: 1500 },
      { text: "Analyzing candlestick patterns...", duration: 1500 },
      { text: "Evaluating momentum for short-term trades...", duration: 1500 },
      { text: "Mapping volatility over time...", duration: 1500 },
      { text: "Applying Fibonacci retracement levels...", duration: 1500 },
      { text: "Identifying convergences/divergences...", duration: 1500 },
      { text: "Comparing multiple timeframes...", duration: 1500 },
      { text: "Filtering noise from significant trends...", duration: 1500 },
      { text: "Generating chart annotations for clarity...", duration: 1500 },
      { text: "Creating visual trade signals...", duration: 1500 },
      { text: "Checking historical backtest results...", duration: 1500 },
      { text: "Blending indicators for strategic insight...", duration: 1500 },
      { text: "Finalizing technical report for decision-making...", duration: 1500 },
    ],
    icon: Zap,
  }
  ,

  sentiment: {
    steps: [
      { text: "Booting Sentiment Agent — mood scanner online...", duration: 1500 },
      { text: "Pulling latest news headlines...", duration: 1500 },
      { text: "Scraping social media buzz...", duration: 1500 },
      { text: "Scanning analyst ratings...", duration: 1500 },
      { text: "Checking press releases and announcements...", duration: 1500 },
      { text: "Analyzing bullish vs bearish mentions...", duration: 1500 },
      { text: "Monitoring trending stock discussions...", duration: 1500 },
      { text: "Calculating sentiment scores...", duration: 1500 },
      { text: "Spotting rumors and hype...", duration: 1500 },
      { text: "Measuring market psychology...", duration: 1500 },
      { text: "Tracking volume of chatter over time...", duration: 1500 },
      { text: "Identifying news impact on stock price...", duration: 1500 },
      { text: "Cross-checking with past trends...", duration: 1500 },
      { text: "Filtering out noise and spam...", duration: 1500 },
      { text: "Assessing short-term market sentiment...", duration: 1500 },
      { text: "Analyzing long-term mood shifts...", duration: 1500 },
      { text: "Summarizing bullish and bearish trends...", duration: 1500 },
      { text: "Visualizing sentiment heatmaps...", duration: 1500 },
      { text: "Generating plain English report...", duration: 1500 },
      { text: "Finalizing sentiment overview for investors...", duration: 1500 },
    ],
    icon: Newspaper,
  }
  ,
  cashflow: {
    steps: [
      { text: "Booting Cashflow Agent — counting every rupee...", duration: 1500 },
      { text: "Pulling operating cash inflows...", duration: 1500 },
      { text: "Tracking outflows: salaries, bills, CAPEX...", duration: 1500 },
      { text: "Checking investing activities...", duration: 1500 },
      { text: "Checking financing activities...", duration: 1500 },
      { text: "Calculating free cash flow...", duration: 1500 },
      { text: "Measuring cash conversion cycle...", duration: 1500 },
      { text: "Checking liquidity ratios...", duration: 1500 },
      { text: "Analyzing working capital changes...", duration: 1500 },
      { text: "Monitoring cash reserves...", duration: 1500 },
      { text: "Detecting cash shortfalls...", duration: 1500 },
      { text: "Analyzing debt repayment capacity...", duration: 1500 },
      { text: "Cross-checking with net profit...", duration: 1500 },
      { text: "Comparing with historical cash trends...", duration: 1500 },
      { text: "Highlighting cash flow anomalies...", duration: 1500 },
      { text: "Visualizing cash inflows/outflows...", duration: 1500 },
      { text: "Summarizing operational efficiency...", duration: 1500 },
      { text: "Checking sustainable cash generation...", duration: 1500 },
      { text: "Creating plain language summary...", duration: 1500 },
      { text: "Final cashflow report ready for review...", duration: 1500 },
    ],
    icon: Wallet,
  }
,
balancesheet: {
  steps: [
    { text: "Opening Balance Sheet Agent — assets and liabilities...", duration: 1500 },
    { text: "Listing current assets...", duration: 1500 },
    { text: "Listing non-current assets...", duration: 1500 },
    { text: "Tracking current liabilities...", duration: 1500 },
    { text: "Tracking long-term liabilities...", duration: 1500 },
    { text: "Checking equity and reserves...", duration: 1500 },
    { text: "Calculating debt-to-equity ratio...", duration: 1500 },
    { text: "Measuring current ratio and liquidity...", duration: 1500 },
    { text: "Analyzing working capital...", duration: 1500 },
    { text: "Checking fixed asset investments...", duration: 1500 },
    { text: "Comparing assets to liabilities...", duration: 1500 },
    { text: "Monitoring reserves and retained earnings...", duration: 1500 },
    { text: "Checking leverage and solvency...", duration: 1500 },
    { text: "Cross-checking with cashflow trends...", duration: 1500 },
    { text: "Evaluating financial stability...", duration: 1500 },
    { text: "Identifying balance sheet risks...", duration: 1500 },
    { text: "Creating visuals for assets vs liabilities...", duration: 1500 },
    { text: "Summarizing key ratios...", duration: 1500 },
    { text: "Translating balance sheet into plain language...", duration: 1500 },
    { text: "Finalizing balance sheet insights report...", duration: 1500 },
  ],
  icon: BarChart3,
}
,
comparison_between_stocks: {
  steps: [
    { text: "Activating Stock Comparison Agent...", duration: 1500 },
    { text: "Loading Stock A and Stock B...", duration: 1500 },
    { text: "Comparing market caps...", duration: 1500 },
    { text: "Checking revenue and profit growth...", duration: 1500 },
    { text: "Evaluating P/E, P/B, and ROE...", duration: 1500 },
    { text: "Scanning debt and leverage levels...", duration: 1500 },
    { text: "Checking dividend yields...", duration: 1500 },
    { text: "Comparing cashflow positions...", duration: 1500 },
    { text: "Overlaying technical charts...", duration: 1500 },
    { text: "Checking RSI and MACD crossovers...", duration: 1500 },
    { text: "Analyzing price trends over time...", duration: 1500 },
    { text: "Monitoring volume patterns...", duration: 1500 },
    { text: "Checking sentiment indicators for both...", duration: 1500 },
    { text: "Benchmarking against sector averages...", duration: 1500 },
    { text: "Highlighting strengths and weaknesses...", duration: 1500 },
    { text: "Comparing historical performance...", duration: 1500 },
    { text: "Generating side-by-side charts...", duration: 1500 },
    { text: "Ranking stocks by key metrics...", duration: 1500 },
    { text: "Summarizing insights in plain English...", duration: 1500 },
    { text: "Final verdict: which stock looks stronger?", duration: 1500 },
  ],
  icon: GitCompare,
}
,
cross_agent_reasoning: {
  steps: [
    { text: "Calling in the market experts...", duration: 1500 },
    { text: "Fundamental Agent checking earnings and red flags...", duration: 1500 },
    { text: "Technical Agent connecting dots and drawing trends...", duration: 1500 },
    { text: "Sentiment Agent reading the market’s mood swings...", duration: 1500 },
    { text: "Agents exchanging notes on valuations...", duration: 1500 },
    { text: "Debating over fundamentals vs technicals...", duration: 1500 },
    { text: "Cross-checking with sentiment for sanity...", duration: 1500 },
    { text: "Identifying conflicting signals...", duration: 1500 },
    { text: "Prioritizing key metrics for clarity...", duration: 1500 },
    { text: "Merging insights from multiple sources...", duration: 1500 },
    { text: "Analyzing peer comparisons...", duration: 1500 },
    { text: "Factoring in recent news impact...", duration: 1500 },
    { text: "Checking long-term vs short-term trends...", duration: 1500 },
    { text: "Calculating weighted scores for each stock...", duration: 1500 },
    { text: "Highlighting red flags and warnings...", duration: 1500 },
    { text: "Building a consolidated view for decision-making...", duration: 1500 },
    { text: "Summarizing the pros and cons...", duration: 1500 },
    { text: "Blending brains for a balanced perspective...", duration: 1500 },
    { text: "Crunching the chaos into one clear call...", duration: 1500 },
    { text: "Final recommendation ready for investor review...", duration: 1500 },
  ],
  icon: BrainCircuit,
}
,
general: {
  steps: [
    { text: "Processing your message...", duration: 1000 },
    { text: "Checking context and keywords...", duration: 1000 },
    { text: "Identifying the type of query...", duration: 1000 },
    { text: "Fetching relevant agent modules...", duration: 1000 },
    { text: "Preparing initial response draft...", duration: 1000 },
    { text: "Polishing tone and clarity...", duration: 1000 },
    { text: "Adding examples if needed...", duration: 1000 },
    { text: "Fact-checking key info...", duration: 1000 },
    { text: "Formatting for readability...", duration: 1000 },
    { text: "Cross-referencing previous interactions...", duration: 1000 },
    { text: "Ensuring consistent style...", duration: 1000 },
    { text: "Optimizing for brevity and clarity...", duration: 1000 },
    { text: "Adding friendly touch where needed...", duration: 1000 },
    { text: "Checking for jargon and simplifying...", duration: 1000 },
    { text: "Finalizing message structure...", duration: 1000 },
    { text: "Running a last-minute consistency check...", duration: 1000 },
    { text: "Adding emojis or highlights if applicable...", duration: 1000 },
    { text: "Preparing to send response...", duration: 1000 },
    { text: "Double-checking keywords against route maps...", duration: 1000 },
    { text: "Crafting a friendly response...", duration: 1000 },
  ],
  icon: Bot,
}
,
unknown: {
  steps: [
    { text: "Parsing your query — hmm, tricky one...", duration: 1500 },
    { text: "Identifying possible intents...", duration: 1500 },
    { text: "Checking for known keywords...", duration: 1500 },
    { text: "Consulting the right market mind for the job...", duration: 1500 },
    { text: "Reviewing historical similar queries...", duration: 1500 },
    { text: "Cross-referencing with knowledge base...", duration: 1500 },
    { text: "Assembling possible answers...", duration: 1500 },
    { text: "Weighing confidence in each suggestion...", duration: 1500 },
    { text: "Filtering out irrelevant info...", duration: 1500 },
    { text: "Prioritizing most likely answers...", duration: 1500 },
    { text: "Checking syntax and formatting...", duration: 1500 },
    { text: "Ensuring readability...", duration: 1500 },
    { text: "Adding fallback options if uncertain...", duration: 1500 },
    { text: "Running context analysis...", duration: 1500 },
    { text: "Double-checking against latest market data...", duration: 1500 },
    { text: "Summarizing insights into simple text...", duration: 1500 },
    { text: "Generating a plain language explanation...", duration: 1500 },
    { text: "Piecing it all together — insights loading...", duration: 1500 },
    { text: "Finalizing response for output...", duration: 1500 },
    { text: "Delivering answer — hope it helps!", duration: 1500 },
  ],
  icon: Bot,
}
,
knowledge_base: {
  steps: [
    { text: "Opening the market playbook...", duration: 1500 },
    { text: "Searching financial knowledge vault...", duration: 1500 },
    { text: "Checking for definitions and explanations...", duration: 1500 },
    { text: "Fetching concept examples...", duration: 1500 },
    { text: "Translating complex jargon into plain English...", duration: 1500 },
    { text: "Looking for historical context...", duration: 1500 },
    { text: "Analyzing market applications...", duration: 1500 },
    { text: "Checking for similar concepts...", duration: 1500 },
    { text: "Compiling key points...", duration: 1500 },
    { text: "Summarizing like a finance nerd with a heart...", duration: 1500 },
    { text: "Highlighting important ratios and formulas...", duration: 1500 },
    { text: "Comparing with industry standards...", duration: 1500 },
    { text: "Preparing visual aids and charts...", duration: 1500 },
    { text: "Cross-referencing trusted sources...", duration: 1500 },
    { text: "Filtering unnecessary info...", duration: 1500 },
    { text: "Organizing content for clarity...", duration: 1500 },
    { text: "Simplifying examples for beginners...", duration: 1500 },
    { text: "Ensuring terminology is consistent...", duration: 1500 },
    { text: "Generating plain English summary...", duration: 1500 },
    { text: "Finalizing knowledge base insights...", duration: 1500 },
  ],
  icon: BookOpen,
}
,
shareholding: {
  steps: [
    { text: "Accessing shareholder registry...", duration: 1500 },
    { text: "Tracking promoter, FII, and DII movements...", duration: 1500 },
    { text: "Analyzing ownership patterns and shifts...", duration: 1500 },
    { text: "Building stake breakdown visuals...", duration: 1500 },
    { text: "Compiling who owns what — and how much...", duration: 1500 },
    { text: "Checking historical shareholding trends...", duration: 1500 },
    { text: "Identifying major stakeholders...", duration: 1500 },
    { text: "Monitoring recent purchases and sales...", duration: 1500 },
    { text: "Analyzing insider trading activity...", duration: 1500 },
    { text: "Tracking institutional investment trends...", duration: 1500 },
    { text: "Evaluating public vs promoter holdings...", duration: 1500 },
    { text: "Highlighting stake concentration risks...", duration: 1500 },
    { text: "Visualizing shareholding pie charts...", duration: 1500 },
    { text: "Comparing against industry peers...", duration: 1500 },
    { text: "Checking regulatory filings...", duration: 1500 },
    { text: "Identifying voting power distribution...", duration: 1500 },
    { text: "Monitoring changes over time...", duration: 1500 },
    { text: "Summarizing ownership insights...", duration: 1500 },
    { text: "Preparing for investor review...", duration: 1500 },
    { text: "Final shareholding report ready...", duration: 1500 },
  ],
  icon: PieChart,
}
,
};