import React from "react";
import IrisLogo from "@/assets/Logo";
import { formatFullDate } from "@/lib/utils";
import PreviewMessage from "./PreviewMessage";
import type { ChatMessage } from "@/redux/slices/chat/types";

interface PdfLayoutProps {
  message: ChatMessage;
}

// This is our standardized template for the PDF content.
const PdfLayout: React.FC<PdfLayoutProps> = ({ message }) => {
  return (
    // We give it a fixed width to ensure consistency in the PDF output.
    <div
      id="pdf-content"
      className="w-[800px] p-10 bg-background text-foreground"
    >
      {/* Header */}
      <div className="flex items-center justify-between pb-4 border-b">
        <div className="flex items-center gap-2">
          <IrisLogo />
          <div>
            <p className="text-lg font-semibold">Iris AI</p>
            <p className="text-sm text-muted-foreground">Financial Analysis</p>
          </div>
        </div>
        <div className="text-right text-sm text-muted-foreground">
          <p>Generated on:</p>
          <p>{formatFullDate(new Date().toISOString())}</p>
        </div>
      </div>

      {/* Main Content Body */}
      <div className="py-8">
        {/* We simply render the PreviewMessage component here! */}
        <PreviewMessage message={message} />
      </div>

      {/* Footer */}
      <div className="pt-4 border-t text-center text-xs text-muted-foreground">
        <p>
          This report is generated by IRIS AI and is for informational purposes
          only. It should not be considered as financial advice.
        </p>
      </div>
    </div>
  );
};

export default PdfLayout;
